### ISSUE TITLE
Set the certificate for OpenVPN as well

### ISSUE THREAD

**Issue by GianlucaUlivi** [foorschtbar/routeros-letsencrypt-docker#5]
Allow the script to set the certificate for OpenVPN Server as well.  
Command to add should be: _/interface ovpn-server server set certificate=$ROUTEROS_FILENAME.pem_0_

**Comment by GianlucaUlivi** [comment]
Command added in pull request #6

**Comment by foorschtbar** [comment]
closed via #6
